version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Bogota"
    open-pull-requests-limit: 10
    assignees:
      - "yeferson59"
      - "Windhoek-dev"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Bogota"
    open-pull-requests-limit: 10
    assignees:
      - "yeferson59"
      - "Windhoek-dev"
